# Generated by Django 4.1.2 on 2022-12-16 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.CharField(choices=[('Болеет', 'Болеет'), ('Командироке', 'Командироке'), ('Работает', 'Работает')], max_length=20)),
                ('Employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_list', to='employee.employee')),
            ],
        ),
    ]
