# Generated by Django 4.1.2 on 2022-12-16 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('inf0_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staffing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zp', models.PositiveIntegerField()),
                ('hours', models.PositiveIntegerField()),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('id_info_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inf0_list.info_list')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_staffing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffing.staffing')),
            ],
        ),
    ]
